<<<<<<< HEAD
# Generated by Django 2.2 on 2020-07-30 03:59
=======
# Generated by Django 2.2.13 on 2020-07-30 04:34
>>>>>>> master

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('persons', '0001_initial'),
=======
        ('services', '__first__'),
        ('persons', '__first__'),
>>>>>>> master
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('geolocation', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('schedule', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.City')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
=======
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
>>>>>>> master
            },
        ),
        migrations.CreateModel(
            name='BranchServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('branch_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.BranchCompany')),
<<<<<<< HEAD
            ],
            options={
                'verbose_name': 'rama servicio',
                'verbose_name_plural': 'rama servicios',
=======
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
            options={
                'verbose_name': 'Rama Servicio',
                'verbose_name_plural': 'Rama Servicios',
>>>>>>> master
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nit', models.BigIntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_image')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('comment', models.TextField(max_length=255)),
                ('branch_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.BranchServices')),
=======
                ('score', models.IntegerField()),
                ('comment', models.TextField(max_length=255)),
                ('branch_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.BranchServices')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Client')),
>>>>>>> master
            ],
            options={
                'verbose_name': 'califacion',
                'verbose_name_plural': 'calificaciones',
            },
        ),
        migrations.AddField(
            model_name='branchcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='branchcompany',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Supervisor'),
        ),
    ]
