# Generated by Django 2.2.13 on 2020-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='score',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
